### ISSUE TITLE
Wersja komercyjna biblioteki

### ISSUE THREAD

**Issue by Lazys** [pkobylski/GPS.Components.Cryptography#1]
Można uzyskać dostęp do wersji komercyjnej/kodu źródłowego biblioteki?

**Comment by pkobylski** [comment]
Jest taka możliwość. Udostępniam bibliotekę komercyjną odpłatnie. Więcej informacji mogę przesłać mailowo.

**Comment by Lazys** [comment]
To proszę o jakiś kontakt do Ciebie, odezwę się.

**Comment by pkobylski** [comment]
kobylski.piotr@gmail.com
